### ISSUE TITLE
Can someone help with installation in Ubuntu 16.04 LTS Terminal?

### ISSUE THREAD

**Issue by raingros** [ocminer/cpuminer-verium#1]
Hi there!

Can someone help with installation in Ubuntu 16.04 LTS Terminal? 

Tried a few times for hours, but couldn't build a working application.

Help is greatly appreciated!

**Comment by raingros** [comment]
That worked, at least with cpuminer-opt (https://github.com/JayDDee/cpuminer-opt):

# Installation on Ubuntu Server 16.04 LTS
sudo apt-get install automake autoconf pkg-config libcurl4-openssl-dev libjansson-dev libssl-dev libgmp-dev
git clone https://github.com/JayDDee/cpuminer-opt
cd cpuminer-opt
./build.sh

# Starting to mine
./cpuminer -a scrypt:1048576 -o stratum+tcp://eu2.poolinat0r.com:7103 -u [username].[worker name] -p [password]

**Comment by ololoch** [comment]
still need help?

**Comment by raingros** [comment]
No, thanks. Works!

**Comment by jjaone** [comment]
Seems that it doesn't work.

When I run:

`./build.sh`

it fails with many similar errors like this in the compile/linker phase:
`
In file included from algo/echo/aes_ni/hash.c:21:0:
algo/echo/aes_ni/vperm.h:53:7: error: called from here
  x  = _mm_shuffle_epi8(*((__m128i*)table + 0), x);\
       ^
algo/echo/aes_ni/hash.c:385:4: note: in expansion of macro ‘TRANSFORM’
    TRANSFORM(_state[i][j], _k_opt, t1, t2);
    ^
In file included from algo/echo/aes_ni/vperm.h:20:0,
                 from algo/echo/aes_ni/hash.c:21:
/usr/lib/gcc/x86_64-linux-gnu/5/include/tmmintrin.h:136:1: error: inlining failed in call to always_inline ‘_mm_shuffle_epi8’: target specific option mismatch
 _mm_shuffle_epi8 (__m128i __X, __m128i __Y)
 ^
In file included from algo/echo/aes_ni/hash.c:21:0:
algo/echo/aes_ni/vperm.h:52:5: error: called from here
  t1 = _mm_shuffle_epi8(*((__m128i*)table + 1), t1);\
     ^
algo/echo/aes_ni/hash.c:385:4: note: in expansion of macro ‘TRANSFORM’
    TRANSFORM(_state[i][j], _k_opt, t1, t2);
    ^
Makefile:2644: recipe for target 'algo/echo/aes_ni/cpuminer-hash.o' failed
make[2]: *** [algo/echo/aes_ni/cpuminer-hash.o] Error 1
make[2]: *** Waiting for unfinished jobs....
mv -f algo/cubehash/.deps/cpuminer-sph_cubehash.Tpo algo/cubehash/.deps/cpuminer-sph_cubehash.Po
mv -f algo/echo/.deps/cpuminer-sph_echo.Tpo algo/echo/.deps/cpuminer-sph_echo.Po
mv -f algo/groestl/.deps/cpuminer-sph_groestl.Tpo algo/groestl/.deps/cpuminer-sph_groestl.Po
make[2]: Leaving directory 'Tools/BlockChain/JayDDDee@cpuminer-opt'
Makefile:4641: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory 'Tools/BlockChain/JayDDDee@cpuminer-opt'
Makefile:787: recipe for target 'all' failed
make: *** [all] Error 2
strip: 'cpuminer': No such file
`

**Comment by deelite** [comment]
@raingros: in which folder do you start

`./cpuminer -a scrypt:1048576 -o stratum+tcp://eu2.poolinat0r.com:7103 -u [username].[worker name] -p [password]`?

I get a 

> cpuminer: command not found

**Comment by LittleCordines** [comment]
seems like cpuminer-opt not working on latest Kubuntu 18.04 LTS.. i get this error : 

/usr/bin/x86_64-linux-gnu-ld: cannot find -lz
collect2: error: ld returned 1 exit status
Makefile:1850: recipe for target 'cpuminer' failed
make[2]: *** [cpuminer] Error 1
make[2]: Leaving directory '/home/vm/cpuminer-opt'
Makefile:5713: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/vm/cpuminer-opt'
Makefile:907: recipe for target 'all' failed
make: *** [all] Error 2
strip: 'cpuminer': No such file

**Comment by muntingbayan** [comment]
it works fine I followed this steps: https://www.youtube.com/watch?v=wm6aGsda4SI

**Comment by dabnpits** [comment]
On Ubuntu 18.04 I had to also install g++ and lib32z1-dev before I was able to run build.sh

`sudo apt-get install g++ lib32z1-dev`

**Comment by jjaone** [comment]
@dabnpits This issue thread is about building and running the software in Ubuntu 16.04, thus your comment about Ubuntu 18.04 and it's dependencies is not relevant here.

**Comment by dabnpits** [comment]
Sorry, my mistake.
